name: ender
favicon: null
layout_spectrum: 0.30624522757716477
typography_spectrum: 0.3420934150926769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1b2b9'
    - '#5894ad'
    - '#8a6f28'
    - '#6e787b'
    - '#9b917a'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
