name: ender
favicon: null
layout_spectrum: 0.36261
typography_spectrum: 0.0187
title: 'Ender is here!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6ca3b8'
    - '#9abbcf'
    - '#726b5c'
    - '#158fab'
    - '#748e97'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
